export const CURRENT_WEATHER_LOAD = 'CURRENT_WEATHER_LOAD';
export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS';
export const CURRENT_WEATHER_FAIL = 'CURRENT_WEATHER_FAIL';

export const FORECAST_5_DAYS_LOAD = 'FORECAST_5_DAYS_LOAD';
export const FORECAST_5_DAYS_SUCCESS = 'FORECAST_5_DAYS_SUCCESS';
export const FORECAST_5_DAYS_FAIL = 'FORECAST_5_DAYS_FAIL';